insert into USER (user_name, password, email) values ('fcloutt0', 'sKwGhPc', 'apittendreigh0@cyberchimps.com');
insert into USER (user_name, password, email) values ('dvicar1', 'EI542PKLq', 'gsmallpeace1@wsj.com');
insert into USER (user_name, password, email) values ('mdainton2', 'glowAAb1vI', 'cduckfield2@google.ca');
insert into USER (user_name, password, email) values ('cbyllam3', '2YDM8bj09', 'bflarity3@cbc.ca');
insert into USER (user_name, password, email) values ('aladson4', 'oa7pr2UO', 'adinneen4@hhs.gov');

insert into POST (title, content, created_on, updated_on, user_id) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '2016-03-20', '2019-12-22', 1);
insert into POST (title, content, created_on, updated_on, user_id) values ('Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2010-04-14', '2019-05-20', 2);
insert into POST (title, content, created_on, updated_on, user_id) values ('Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', '2014-01-08', '2019-10-10', 3);
insert into POST (title, content, created_on, updated_on, user_id) values ('Morbi porttitor lorem id ligula.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '2016-01-28', '2018-03-05', 4);
insert into POST (title, content, created_on, updated_on, user_id) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2012-04-19', '2019-05-31', 4);
insert into POST (title, content, created_on, updated_on, user_id) values ('Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2014-04-30', '2019-11-25', 4);
insert into POST (title, content, created_on, updated_on, user_id) values ('In hac habitasse platea dictumst.', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', '2011-11-06', '2018-11-15', 5);
insert into POST (title, content, created_on, updated_on, user_id) values ('Etiam faucibus cursus urna. Ut tellus.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2012-11-02', '2019-01-13', 5);
insert into POST (title, content, created_on, updated_on, user_id) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '2012-03-19', '2018-12-14', 5);
insert into POST (title, content, created_on, updated_on, user_id) values ('Maecenas rhoncus aliquam lacus.', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '2013-03-29', '2019-12-26', 5);
